apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: esquire-service-dev
      namespace: dev
  - path: service-patch.yaml
    target:
      kind: Service
      name: esquire-service-dev
      namespace: dev
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: esquire-service-dev
      namespace: dev
